DROP DATABASE flashlab;

CREATE DATABASE flashlab;
USE flashlab;

CREATE TABLE users (
idUti SMALLINT PRIMARY KEY AUTO_INCREMENT,
prenom VARCHAR(30) NOT NULL,
nom VARCHAR(30) NOT NULL,
mail VARCHAR(30) NOT NULL,
password CHAR(70) NOT NULL);

CREATE TABLE exemple (
id SMALLINT PRIMARY KEY AUTO_INCREMENT,
element VARCHAR(30) NOT NULL,
colonne VARCHAR(30) NOT NULL,
ligne VARCHAR(30) NOT NULL);