- hosts: all
  connection: local
  user: remote
  gather_facts: false
  become_user: true

#  roles:
#    - role: network
#      network_interfaces:
#        - device: eth0
#          auto: true
#          family: inet
#          method: static
#          address: 10.10.10.10
#          network: 10.10.10.0
#          netmask: 255.255.255.0
#          gateway: 10.10.10.254
#          mtu: 1500

  tasks:
    - vsphere_guest:
        vcenter_hostname: 'XXXXXX'
        username: 'XXXXXX'
        password: 'XXXXXX'
        validate_certs: false
        guest: 'IV-STUP-FLA_FIRE'
        from_template: yes
        template_src: "IV-STUV-FLA_FIRE"
        cluster: "CLUSTER"
        resource_pool: "XXXXXX"
        vm_extra_config:
          notes: "Firewall for FlashLAB"
          power_on_after_clone: yes
        vm_disk:
          disk1:
            size_gb: '5'
            type: 'thin'
            datastore: 'XXXXXX'
        vm_nic:
          nic1:
            type: vmxnet3
            network_type: standard
        vm_hardware:
          memory_mb: 4096
          num_cpus: '2'
          osid: 'IV-STUP-FLA_FIRE'
          scsi: paravirtual
        esxi:
          datacenter: "XXXXXX"
          hostname: "XXXXXX"
...
