---

- hosts: all
  connection: local
  user: remote
  gather_facts: false
  become_user: true

  tasks:
    - vsphere_guest:
        vcenter_hostname: 'XXXXXX'
        username: 'XXXXXX'
        password: 'XXXXXX'
        validate_certs: false
        guest: 'IV-STUP-FLA_WEB'
        from_template: yes
        template_src: "IV-STUV-FLA_WEB"
        cluster: "CLUSTER"
        resource_pool: "XXXXXX"
        vm_extra_config:
          notes: "Web server for FlashLAB"
          power_on_after_clone: yes
        vm_disk:
          disk1:
            size_gb: '5'
            type: 'thin'
            datastore: 'XXXXXX'
        vm_nic:
          nic1:
            type: vmxnet3
            network_type: standard
        vm_hardware:
          memory_mb: 4096
          num_cpus: '2'
          osid: 'IV-STUP-FLA_WEB'
          scsi: paravirtual
        esxi:
          datacenter: "XXXXXX"
          hostname: "XXXXXX"
...
